### ISSUE TITLE
Single point in time stats do not remove unchecked regions.

### ISSUE THREAD

**Issue by david-macias** [blrchen/aws-speed-test#2]
If you select multiple regions then unselect them and hover over a point in time you still see the unselected region stats showing all zeros.

david

![Screenshot 2021-11-09 160140](https://user-images.githubusercontent.com/6012207/141004045-6c65bdb3-3664-4d2f-9edd-ab09956d83da.png)

**Comment by blrchen** [comment]
Closing as this has been fixed for a while.
